### ISSUE TITLE
./make.sh build 报错了，fatal error: 'ext/swoole/include/swoole_version.h' file not found

### ISSUE THREAD

**Issue by abo1016** [swoole/swoole-cli#10]
![image](https://user-images.githubusercontent.com/18510237/205429985-a6dfafda-f5c5-4729-9744-2956b24317f5.png)

**Comment by abo1016** [comment]
![image](https://user-images.githubusercontent.com/18510237/205430041-a135817d-8b29-4a81-ad4c-4028d5975823.png)
./make.sh  config   
configure: WARNING: unrecognized options: --enable-swoole, --enable-swoole-curl, --enable-cares, --with-brotli-dir

**Comment by jingjingxyk** [comment]
> ![image](https://user-images.githubusercontent.com/18510237/205430041-a135817d-8b29-4a81-ad4c-4028d5975823.png) ./make.sh config configure: WARNING: unrecognized options: --enable-swoole, --enable-swoole-curl, --enable-cares, --with-brotli-dir

需要拉取子模块 https://github.com/swoole/swoole-cli/blob/main/.gitmodules
```
git submodule update --init --recursive

```

REAMEM.md  暂时不全，等待补全
```shell

php prepare.php +inotify 

./make.sh docker-bash

./make.sh all-library
./make.sh config
./make.sh build
./make.sh archive
```

**Comment by matyhtf** [comment]
欢迎提交 pr
