### ISSUE TITLE
configure:31121: error: Unable to locate gmp.h

### ISSUE THREAD

**Issue by QeeZer** [swoole/swoole-cli#11]
version: v5.0.1 / current main

command: 
`./make.sh config`

```
configure:27873: $? = 0
configure:30163: checking for GNU gettext support
configure:30200: result: no
configure:30892: checking for GNU MP support
configure:30929: result: yes
configure:31121: error: Unable to locate gmp.h
```

**Comment by QeeZer** [comment]
In amd64 ubuntu 22.04 x11

**Comment by NathanFreeman** [comment]
It is possible that the gmp.tar.gz is not completely downloaded due to network problems.

**Comment by matyhtf** [comment]
You should compile gmp first

```shell
./make.sh gmp
```

**Comment by QeeZer** [comment]
> You should compile gmp first
> 
> ```shell
> ./make.sh gmp
> ```

checking if iconv supports errno... no
configure: error: iconv does not support errno
