### ISSUE TITLE
咨询一下，我要编译arm环境，也是参考linux构建吗

### ISSUE THREAD

**Issue by netyum** [swoole/swoole-cli#137]
咨询一下，我要编译arm环境，也是参考linux构建吗

需要自己build镜像是吧

**Comment by jingjingxyk** [comment]
> 咨询一下，我要编译arm环境，也是参考linux构建吗
> 
> 需要自己build镜像是吧

 都不用修改，你直接切换到 ARM linux 环境下，直接就能构建

**Comment by jingjingxyk** [comment]
这里 https://github.com/swoole/swoole-src/releases  
和 这里 https://www.swoole.com/download  
有构建好的

**Comment by netyum** [comment]
已经编译成功，不过进容器后的操作只能用sh，不能用bash，没具体看
