### ISSUE TITLE
./make.sh build报错 fatal error: 'brotli/encode.h' file not found

### ISSUE THREAD

**Issue by cokeTsang** [swoole/swoole-cli#17]
执行步骤：
git submodule update --init --recursive
php prepare.php
./make.sh docker-bash
./make.sh all-library
./make.sh config
./make.sh build

![image](https://user-images.githubusercontent.com/16095159/210768911-7e8bddcd-212c-4a5c-be05-f8f35db44c6a.png)

**Comment by jingjingxyk** [comment]
重新编译 brotli 试试，以及看看报错信息

```shell
sh make.sh brotli
```

通过实验，得到如下信息：
```text 

iconv 库不能使用 pkg-config 命令
bzip2 库不能使用 pkg-config 命令 

mbstring // 依赖 oniguruma

 intl  // 依赖 ICU, 安装ICU 

 mongodb  //依赖 openssl zlib

readline 依赖 ncurses

```

写以上信息，意思就是你可以把一些扩展注释了，重新静态编译

**Comment by cokeTsang** [comment]
> @cokeTsang
> 
> 重新编译 brotli 试试，以及看看编译`brotli`具体报错信息
> 
> ```shell
> sh make.sh brotli
> ```
> 
> 通过实验，得到如下信息：
> 
> ```
> 
> iconv 库不能使用 pkg-config 命令
> bzip2 库不能使用 pkg-config 命令 
> 
> mbstring //    依赖 oniguruma 库
> 
> intl  // 依赖 ICU 库 , 安装ICU 
> 
> mongodb  //依赖 openssl zlib 库
> 
> readline 依赖 ncurses 库
> ```
> 
> 写以上信息，意思就是你可以把一些扩展注释了，重新静态编译，通过以后，再来解决编译不通过的地方
> 
> 每次增加扩展或者屏蔽扩展
> 
> ```shell
> # 比如屏蔽扩展  intl  opcache pcntl imagick gd
> php prepare.php  -intl  -opcache -pcntl -imagick -gd
> ```

@jingjingxyk 受您的提醒看到make.sh可以编译指定扩展。
按照make.sh的错误提示发现是我的brotli-1.0.9.tar.gz不完整。
手动删除pool里面的brotli-1.0.9.tar.gz重新prepare下载后再次执行：
```
./make.sh brotli
./make.sh build
```
编译成功，非常感谢！
