### ISSUE TITLE
swoole-cli windows 版，如何解决  /cygdrive/c/  路径不存在问题，是不是必须安装cygwin 环境?

### ISSUE THREAD

**Issue by jingjingxyk** [swoole/swoole-cli#19]
配置系统变量PATH 以后，是可以使用的

```bash
# 设置软连接

mklink  "C:\Users\biubiu\Downloads\swoole-cli-v5.0.1-cygwin64\bin\php.exe"  "C:\Users\biubiu\Downloads\swoole-cli-v5.0.1-cygwin64\bin\swoole-cli.exe" 

swoole-cli -v
php -v

```
 get_dir.php 
```php
<?php

echo __DIR__;

```

```bash
php get_dir.php

```
但是当使用魔术变量 `__DIR__`  时，返回的路径不存在

![image](https://user-images.githubusercontent.com/6836228/218389333-b0a1580a-c084-42a8-bd2a-ea70647da141.png)

操作系统是不是还必须安装 [`cygwin`](https://cygwin.com/) ？ 

安装cygwin
```bash

setup-x86_64.exe -B -O -s http://cygwin.mirror.constant.com


```

cygwin 是否有版本要求？

**Comment by matyhtf** [comment]
在 cygwin 环境下是不支持 windows 风格路径的，比如 "C:\Users\biubiu" ，需要将 `C:\` 替换为 `/cygdriver/c/` 
swoole-cli 中的 is_dir file_* 相关函数是可以读取这个路径的，但无法使用 shell_exec 执行 linux 命令，这些命令并没有包含在 swoole-cli cygwin 包中，若需要完整的系统环境，需要安装 cygwin
