### ISSUE TITLE
cygwin64 编译本项目时，需要删除 main/main.c  文件中的2行代码，才能链接通过，不知道怎么解决这个问题

### ISSUE THREAD

**Issue by jingjingxyk** [swoole/swoole-cli#20]
链接阶段找不到 结构体  ` zend_extension_entry`

main/main.c 需要删除的行是： 2263,2264 行

```c
	/* start Zend extensions */
	extern zend_extension ;
	# zend_register_extension(&zend_extension_entry, NULL);
	# zend_startup_extensions();

```

错误信息：

![image](https://user-images.githubusercontent.com/6836228/218440286-62786a7d-9d57-47b3-9014-0eb15fe635df.png)

删除两行代码以后，可以编译通过
``` bash
test -f main/main.c.backup ||  sed -i.backup '2263,2264d' main/main.c

```

![截图 2023-02-13 18-57-41](https://user-images.githubusercontent.com/6836228/218440519-7f84b8fc-91b5-4306-9cce-19c8ca736574.png)

**Comment by matyhtf** [comment]
执行 `./buildconf --force` 加载 opcache 的配置文件
