### ISSUE TITLE
make.sh all-library报错了

### ISSUE THREAD

**Issue by wenzhizhong** [swoole/swoole-cli#320]
66ed74d6404c:/work# bash make.sh all-library
build openssl
                             # ./Configure LIST
                ./config  -static --static no-shared  enable-tls1_3 --release --prefix=/usr/local/swoole-cli/openssl --libdir=/usr/local/swoole-cli/openssl/lib

Configuring OpenSSL version 3.0.8+quic for target linux-x86_64
Using os-specific seed configuration
Created configdata.pm
Running configdata.pm
Created Makefile.in
Created Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL.md file first)      ***
***                                                                ***
**********************************************************************
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
make: /bin/sh: Operation not permitted
make: *** [Makefile:3493: include/crypto/bn_conf.h] Error 127
[openssl] [make FAILURE]

**Comment by jingjingxyk** [comment]
用的那个分支？ 是main 分支吗？ 
在什么环境下编译的？  是alpine 3.17 吗？

完成的编译命令是？


可以尝试: 把 openssl-3.0.8-quic1.tar.gz 删除，重新生成构建脚本
```shell

rm -rf  pool/lib/openssl-3.0.8-quic1.tar.gz   

composer update 
php prepare.php  

```

**Comment by jingjingxyk** [comment]
用main 分支：
构建步骤：
```shell
# 准备PHP 运行时 （看提示，把 PHP 运行时导入环境变量PATH ）
sh setup-php-runtime.sh

# 准备运行脚本（目的是为了生成生成进入容器、构建容器的脚本）【容器外】
composer update  
php prepare.php --without-docker --skip-download=1

# 查看用的构建命令
bash make.sh -h

# 构建容器运行环境
bash make.sh docker-build
# 启动容器运行环境，并进入容器
bash make.sh docker-bash

# 准备运行脚本（ 下载各依赖库源码，生成构建脚本）【容器内】
composer update  
php prepare.php   +inotify +apcu +ds +xlswriter +ssh2  --with-swoole-pgsql=1

# 静态编译依赖库
bash make.sh  all-library 
# 静态编译 PHP 预处理
bash make.sh config 
# 静态编译PHP （汇编、编译、链接）
bash make.sh build 
# 静态编译PHP （打包）
bash make.sh archive 

```

**Comment by jingjingxyk** [comment]
单独编译 openssl

```shell

bash make.sh openssl

```
