### ISSUE TITLE
windows 版的 swoole-cli.exe 不支持 cli_set_process_title，函数存在，但是一直报错

### ISSUE THREAD

**Issue by pifeifei** [swoole/swoole-cli#339]
![image](https://github.com/swoole/swoole-cli/assets/45787170/7152fec6-b4ed-4a74-a018-f9985b8bab0a)

**Comment by jingjingxyk** [comment]
@pifeifei   目录不对哈，
![image](https://github.com/swoole/swoole-cli/assets/6836228/8c04308c-3a05-467f-9229-5c68e60dcb75)

**Comment by pifeifei** [comment]
> @pifeifei 目录不对哈， ![image](https:user-images.githubusercontent.com/6836228/262646551-8c04308c-3a05-467f-9229-5c68e60dcb75.png)

我这个是 windows 版本的，使用swoole 就会变成这个目录

**Comment by jingjingxyk** [comment]
@pifeifei  我尝试了以下，发现并不影响使用  （应该属于兼容信问题）

因为swoole 在 windows 环境下的实现，使用了[cygwin ](https://cygwin.com/)来实现的

**Comment by jingjingxyk** [comment]
![VirtualBox_win7-msys2-1_24_08_2023_11_52_19](https://github.com/swoole/swoole-cli/assets/6836228/d8cf835c-f4a2-4654-866b-60948b9d5c02)

**Comment by jingjingxyk** [comment]
@pifeifei  windows 上推荐使用 WSL2

**Comment by jingjingxyk** [comment]
@pifeifei  https://wenda.swoole.com/detail/108743   拉到文档最后，可能对你有用。

**Comment by pifeifei** [comment]
> @pifeifei https://wenda.swoole.com/detail/108743 拉到文档最后，可能对你有用。

谢谢，这些我已经使用了

git bash 中 composer.bat 有时候不太好用，需要带上 bat， 我直接做了个连接就可以了，  `mklink composer composer.phar`
