### ISSUE TITLE
TODO 支持更多的库

### ISSUE THREAD

**Issue by matyhtf** [swoole/swoole-cli#35]
CURL
---
- zstd
- nghttp2 
- nghttp3

**Comment by jingjingxyk** [comment]
正在尝试

**Comment by jingjingxyk** [comment]
初步验证完成

看依赖顺序： https://github.com/jingjingxyk/swoole-cli/blob/new_dev/library_install_builder.php

libzstd:  https://github.com/jingjingxyk/swoole-cli/blob/2f4207b4f66bbff0010fda7772959272ead90240/library_install_builder_conf.php#L859

nghttp3:  https://github.com/jingjingxyk/swoole-cli/blob/2f4207b4f66bbff0010fda7772959272ead90240/library_install_builder_conf.php#L1396 

nghttp2: https://github.com/jingjingxyk/swoole-cli/blob/2f4207b4f66bbff0010fda7772959272ead90240/library_install_builder_conf.php#L1021

c-cares 也可以启用了

![image](https://user-images.githubusercontent.com/6836228/219900808-72a0dbaf-939d-45cc-bd78-e3d1643c52e4.png)
![image](https://user-images.githubusercontent.com/6836228/219900815-7b093a95-5870-4b87-9899-f75fcafe0713.png)

特别关注： brotli 需要补上一句命令：

```
cmake --build . --config Release --target install
```
![image](https://user-images.githubusercontent.com/6836228/219900865-ff302900-271a-442f-9393-42b11ebefb1f.png)
