### ISSUE TITLE
使用 Swoole\WebSocket\Client 提示没有

### ISSUE THREAD

**Issue by rhl88** [swoole/swoole-cli#361]
代码如下，为什么呢？
`<?php
$host = '127.0.0.1'; // WebSocket服务器的IP地址
$port = 8001; // WebSocket服务器的端口
$clientId = '221'; // 您的客户端ID
$secretKey = 'your_secret_key'; // 您的密钥

// 创建WebSocket客户端
$client = new Swoole\WebSocket\Client($host, $port);

// 连接到WebSocket服务器
if (!$client->connect()) {
    echo "连接失败\n";
    exit;
}

// 发送带有客户端ID和密钥的验证消息
$verificationMessage = json_encode(['id' => $clientId, 'key' => $secretKey]);
$client->push($verificationMessage);

// 接收并处理来自服务器的消息
while (true) {
    $response = $client->recv();
    if ($response === false) {
        echo "连接已关闭\n";
        break;
    } elseif ($response === '') {
        // 使用ping消息保持连接活动
        $client->push('ping');
    } else {
        echo "从服务器接收到： " . $response->data . "\n";
    }
}

// 关闭连接
$client->close();`

**Comment by jingjingxyk** [comment]
协程写法： 
写法例子： [HTTP/WebSocket客户端](https://wiki.swoole.com/#/coroutine_client/http_client)

```php
use Swoole\Coroutine;
use Swoole\Coroutine\Http\Client;
use function Swoole\Coroutine\run;

run(function () {
    $client = new Client('127.0.0.1', 9501);
    $ret = $client->upgrade('/');   # 最关键点就是这里了。
    if ($ret) {
        while(true) {
            $client->push('hello');
            var_dump($client->recv());
            Coroutine::sleep(0.1);
        }
    }
});

```

**Comment by jingjingxyk** [comment]
老版本异步 swoole websocket client https://wiki.swoole.com/wiki/page/p-http_client.html

这个我没有用过。

**Comment by jingjingxyk** [comment]
搜索引擎 搜索信息： 
 https://www.baidu.com/s?ie=utf-8&wd=WebSocket+%E5%AE%A2%E6%88%B7%E7%AB%AF%20%20site:swoole.com

https://cn.bing.com/search?q=WebSocket+%E5%AE%A2%E6%88%B7%E7%AB%AF%20site:swoole.com


https://www.google.com/search?q=WebSocket+%E5%AE%A2%E6%88%B7%E7%AB%AF%20site:swoole.com
