### ISSUE TITLE
./make.sh build 构建出错，已经试过很多次就一直卡在这里，不知道是哪个步骤不对，请大佬指点一下，在ubuntu22.04版本下构建

### ISSUE THREAD

**Issue by findnr** [swoole/swoole-cli#362]
li/icu/include -I/usr/local/swoole-cli/libxslt/include -I/usr/local/swoole-cli/libxml2/include/libxml2 -I/usr/local/swoole-cli/libiconv/include -I/usr/local/swoole-cli/gmp/include -I/usr/local/swoole-cli/libsodium/include -I/usr/local/swoole-cli/ncurses/include/ncursesw -I/usr/local/swoole-cli/ncurses/include -I/usr/local/swoole-cli/readline/include -I/usr/local/swoole-cli/libjpeg/include -I/usr/local/swoole-cli/freetype/include/freetype2 -I/usr/local/swoole-cli/libpng/include/libpng16 -I/usr/local/swoole-cli/libwebp/include -I/usr/local/swoole-cli/libyaml/include -I/usr/local/swoole-cli/imagemagick/include/ImageMagick-7 -I/usr/local/swoole-cli/zlib/include -I/usr/local/swoole-cli/openssl/include  -fno-common -Wstrict-prototypes -Wall -Wextra -Wno-strict-aliasing -Wno-unused-parameter -Wno-sign-compare -Wall -pthread -g -O2 -fvisibility=hidden -DZEND_SIGNALS  -fno-ident -Os -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -c /work/main/streams/filter.c -o main/streams/filter.lo  -MMD -MF main/streams/filter.dep -MT main/streams/filter.lo
/work/main/streams/cast.c:137:2: error: incompatible function pointer types initializing 'cookie_seek_function_t *' (aka 'int (*)(void *, long *, int)') with an expression of type 'int (void *, zend_off_t, int)' (aka 'int (void *, long, int)') [-Wincompatible-function-pointer-types]
        stream_cookie_seeker, stream_cookie_closer
        ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Makefile:3683: main/streams/cast.lo] Error 1
make: *** Waiting for unfinished jobs....
/work/bin/swoole-cli: cannot open `/work/bin/swoole-cli' (No such file or directory)
readelf: Error: '/work/bin/swoole-cli': No such file

**Comment by findnr** [comment]
![image](https://github.com/swoole/swoole-cli/assets/3909023/140512a2-5dd1-4682-b799-da2c64961ab6)

**Comment by jingjingxyk** [comment]
把swoole 版本切换为 v5.0.3

**Comment by jingjingxyk** [comment]
linux 版本请在容器里构建。

**Comment by jingjingxyk** [comment]
你用的那个分支构建的？

**Comment by jingjingxyk** [comment]
切换 swoole 分支以后，别忘了执行  `make clean `

**Comment by findnr** [comment]
非常感谢，已经编译成功。大佬辛苦啦！！！

**Comment by jingjingxyk** [comment]
可切换 PHP 版本 使用 `build_native_php` 分支 。

GD库支持 avif 格式的图片 ，使用 `build_native_php`  分支 或者  `experiment` 分支 

各分支的区别简述： 
https://github.com/swoole/swoole-cli/issues/273

**Comment by findnr** [comment]
好的，谢谢了
