### ISSUE TITLE
./make.sh config 成功，但 ./make.sh build 报错

### ISSUE THREAD

**Issue by SteelQ** [swoole/swoole-cli#385]
./make.sh config 执行后成功输出 Thank you for using PHP

随后执行 ./make.sh config 报错，如下图：

![image](https://github.com/swoole/swoole-cli/assets/6867980/1295475d-907e-4123-b8e5-ec64cd66e368)

**Comment by jingjingxyk** [comment]
排查依赖库的构建。或者使用 experiment 分支，可以看到构建过程中的错误
