### ISSUE TITLE
高版本macOS构建的cli无法在低版本OS中使用

### ISSUE THREAD

**Issue by 1307super** [swoole/swoole-cli#39]
在低于macOS 12下 使用swoole-cli 会提示swoole-cli是构建于macOS 12, 导致无法使用

**Comment by jingjingxyk** [comment]
你可以自己构建一个版本，看看

**Comment by 1307super** [comment]
要得, 我试试看

**Comment by jingjingxyk** [comment]
MAC OS 上执行这个命令就可以开始构建了
```bash 

php prepare.php --without-docker=1

sh make.sh all-library

sh make.sh config 
sh make.sh build 


```

更多信息，看这 https://github.com/swoole/swoole-cli/blob/main/docs/macOS.md

**Comment by 1307super** [comment]
> MAC OS 上执行这个命令就可以开始构建了
> 
> ```shell
> php prepare.php --without-docker=1 @macos
> 
> sh make.sh all-library
> 
> sh make.sh config 
> sh make.sh build 
> ```
> 
> 更多信息，看这 https://github.com/swoole/swoole-cli/blob/main/docs/macOS.md
> 
> @1307super

跟着文档大部分问题解决了, 在make.sh build的时候 报错了, 在执行前已手动执行了 export PKG_CONFIG_PATH=xxxx(make.sh 里的) 在对应的cares/include 也有ares.h 能帮忙看看这个问题怎么解决吗
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/35326304/220805816-26537893-6c6f-4a00-88b8-c2c05943ef85.png">

**Comment by jingjingxyk** [comment]
@1307super  类似这样解决：https://github.com/swoole/swoole-cli/blob/098515042355c31cc46b50ee2af359fe59491740/sapi/make.php#L119
