### ISSUE TITLE
借助本项目构建的依赖库，编译PHP其他版本--例子PHP7.4 ，PHP 8.20

### ISSUE THREAD

**Issue by jingjingxyk** [swoole/swoole-cli#41]
比如：php 7.4 、 php 8.20 

第一步：运行已经构建好依赖库的容器：
> 这两个容器镜像都是一样的，区别是：容器镜像的生成过程不同
> 前者通过 `docker commit `  生成
> 后者通过 ` Dockerfile ` 分步构建生成
```bash
#!/bin/env sh 
__DIR__=$(
  cd "$(dirname "$0")"
  pwd
)

image=phpswoole/swoole-cli-builder:1.6

image=registry.cn-beijing.aliyuncs.com/jingjingxyk-public/app:build-swoole-cli-build-dependencies-alpine-edge-20230226T074232Z


docker run --rm --name  swoole-cli-build-dev-all-dependencies-container -d -v ${__DIR__}:/work -w /work $image tail -f /dev/null


```

第二步：静态编译PHP 

这三个分支，选择自己需要的，他们之间变化并不大哈。自己修改PHP 版本就行
[build_native_php](https://github.com/jingjingxyk/swoole-cli/tree/build_native_php)
[build_php_8.2](https://github.com/jingjingxyk/swoole-cli/tree/build_php_8.2)
[build_php_7.4](https://github.com/jingjingxyk/swoole-cli/tree/build_php_7.4)
[build_php_7.3](https://github.com/jingjingxyk/swoole-cli/tree/build_php_7.3)  需要更换为GCC 、glibc

步骤也没变
```bash 
php prepare.php  
sh make.sh all_library
sh make.sh php_src   # 这一步执行下载PHP 源码，并把需要的扩展的源码拷贝到 PHP源码目录
sh amke.sh config 
sh make.sh build 
sh make.sh archive
```

**Comment by ikilobyte** [comment]
7.0、7.1这种低版本也可以吗？

**Comment by ikilobyte** [comment]
@jingjingxyk

**Comment by jingjingxyk** [comment]
@ikilobyte  当然可以了

**Comment by ikilobyte** [comment]
@jingjingxyk 

#!/bin/env sh 
__DIR__=$(
  cd "$(dirname "$0")"
  pwd
)

image=phpswoole/swoole-cli-builder:1.6

image=registry.cn-beijing.aliyuncs.com/jingjingxyk-public/app:build-swoole-cli-build-dependencies-alpine-edge-20230226T074232Z


docker run --rm --name  swoole-cli-build-dev-all-dependencies-container -d -v ${__DIR__}:/work -w /work $image tail -f /dev/null

执行这个脚本就行了是吗

**Comment by jingjingxyk** [comment]
@ikilobyte 是的，静态编译的依赖库已经构建好


`docker exec -it swoole-cli-build-dev-all-dependencies-container sh `  就可以进入容器了

其他脚本在这里：https://github.com/jingjingxyk/swoole-cli/tree/new_dev_build/build-tools/php-7

**Comment by ikilobyte** [comment]
@jingjingxyk 有好几个脚本，需要执行哪几个？

**Comment by jingjingxyk** [comment]
这是步骤简述： https://github.com/crazywhalecc/static-php-cli/issues/22#issue-1534357988

这个容器相当于把第4步提前完成了

需要这些：

下载源码： https://github.com/jingjingxyk/swoole-cli/blob/new_dev_build/build-tools/php-7/download-sourcecode.sh
静态编译PHP 准备构建参数： https://github.com/jingjingxyk/swoole-cli/blob/new_dev_build/build-tools/php-7/build-config-php-7.sh
执行静态编译PHP：  https://github.com/jingjingxyk/swoole-cli/blob/new_dev_build/build-tools/php-7/build-make-php-7.sh

**Comment by ikilobyte** [comment]
嗯，执行`build-config-php-7.sh`报错了，我需要的php版本是7.0.21（老项目），`download-sourcecode.sh` 执行成功了

```bash
checking whether to include code coverage symbols... no
checking whether to enable bc style precision math functions... yes
checking for BZip2 support... yes
checking for BZ2_bzerror in -lbz2... yes
checking whether to enable calendar conversion support... no
checking whether to enable ctype functions... yes
checking for cURL support... yes
checking for cURL in default path... not found
configure: error: Please reinstall the libcurl distribution -
    easy.h should be in <curl-dir>/include/curl/

**Comment by ikilobyte** [comment]
download-sourcecode.sh里面的也`version`变量也改成了`php-7.0.21`

**Comment by jingjingxyk** [comment]
很好解决啊，除非PHP 就不支持，那就得降依赖库的版本

参考这里解决：     [package_names="readline icu-i18n  icu-io   icu-uc libpq libffi"](https://github.com/jingjingxyk/swoole-cli/blob/44e01cf42298278059f1af38e8b3541b1ea3db50/sapi/make.php#L192)

填上类似这个：
```bash
package_names="${package_names} libcurl"

```

**Comment by jingjingxyk** [comment]
刚验证了以下：7.0 和7.4 参数配置是有差异的。7.0 版本curl需要这样写`--with-curl=/usr/curl`, 7.4 版本curl 是这样`--with-curl` 没有参数

调试，按照错误提示，修正就行
```bash 
./configure --help | grep curl
```

**Comment by ikilobyte** [comment]
@jingjingxyk 刚试了一下，7.0的大把报错，，根本用不了

**Comment by jingjingxyk** [comment]
@ikilobyte  我看了，并且尝试了，改改配置就能通过，不能通过的就只能降低依赖库版本

https://github.com/jingjingxyk/swoole-cli/blob/new_dev_build/build-tools/php-7/build-config-php-7.0.sh

自己修改这些配置
```bash 

--with-openssl=/usr/openssl \
--with-curl=/usr/curl \
--enable-zip \
--with-libzip=/usr/libzip \
--enable-libxml \
--with-libxml-dir=/usr/libxml2 \
--with-xsl=/usr/libxslt/ \
--with-jpeg-dir=/usr/libjpeg \
--with-freetype-dir=/usr/freetype \
--with-webp-dir=/usr/libwebp \
--with-gd=/usr/

```

**Comment by jingjingxyk** [comment]
@ikilobyte  想用就自己改 配置文件，以及降低扩展的版本，或者降低依赖库的版本

**Comment by jingjingxyk** [comment]
自己对比和7.4的区别

```bash 
./configure --help | grep curl
./configure --help | grep zip
./configure --help | grep libxml
./configure --help | grep gd
./configure --help | grep jpeg
./configure --help | grep freetype
./configure --help | grep webp
./configure --help | grep xslt
./configure --help | grep gd
./configure --help | grep openssl
./configure --help | grep yaml
```
你可以看下参数的区别就知道了。和7.4版本 参数差别很大的

**Comment by jingjingxyk** [comment]
更多变更信息： https://www.php.net/manual/zh/migration74.other-changes.php

**Comment by 1307super** [comment]
大佬, macos能编译7.x版本吗?

**Comment by jingjingxyk** [comment]
[build_native_php](https://github.com/jingjingxyk/swoole-cli/tree/build_native_php)
[build_php_8.2](https://github.com/jingjingxyk/swoole-cli/tree/build_php_8.2)
[build_php_7.4](https://github.com/jingjingxyk/swoole-cli/tree/build_php_7.4)

他们之间变化并不大哈

**Comment by jingjingxyk** [comment]
> 

php7.3-7.4 主要配置参数有变化： https://www.php.net/manual/zh/migration74.other-changes.php

也就是需要修改: [conf.d](https://github.com/jingjingxyk/swoole-cli/tree/build_native_php/conf.d) 里面的配置

**Comment by jingjingxyk** [comment]
php 7.4 以前 使用 gcc 编译

**Comment by 1307super** [comment]
> 这三个分支，选择自己需要的，他们之间变化并不大哈。自己修改PHP 版本就行 [build_native_php](https://github.com/jingjingxyk/swoole-cli/tree/build_native_php) [build_php_8.2](https://github.com/jingjingxyk/swoole-cli/tree/build_php_8.2) [build_php_7.4](https://github.com/jingjingxyk/swoole-cli/tree/build_php_7.4)
> 
> ```shell
> php prepare.php  
> sh make.sh all_library
> sh make.sh php_src   # 这一步执行下载PHP 源码，并把需要的扩展的源码拷贝到 PHP源码目录
> sh amke.sh config 
> sh make.sh build 
> sh make.sh archive
> ```

在macos下:
使用sh make.sh all_library  的时候 libssh2报错:

./make.sh: line 758: -DCRYPTO_BACKEND=OpenSSL: command not found

openssl版本:
LibreSSL 2.8.3

大佬 这是啥问题呀? 我将-DCRYPTO_BACKEND=/xxx/.swoole-cli/openssl 也不行

**Comment by jingjingxyk** [comment]
这是bug ，https://github.com/swoole/swoole-cli/pull/109/files

**Comment by 1307super** [comment]
> @1307super 这是bug ，看这里 https://github.com/swoole/swoole-cli/pull/109/files ，等待和并分支
> 
> 详见： https://github.com/swoole/swoole-cli/pull/109/files#diff-679f41e70959bcd874f03c79fa4531e333a36af24a72f6b5000314b6a4590323R144
> 
> 或者自己手动修复一下即可： https://github.com/swoole/swoole-cli/blob/main/conf.d/curl.php#L143
> 
> conf.d/curl.php 143 行， 多了一个换行符 144行少一个换行符

感谢, 这一步跑完了, 走config的时候 最后出现
If configure fails try --with-xpm-dir=<DIR>
configure: error: freetype-config not found.

我重新编译了freetype  还是不行噶

**Comment by jingjingxyk** [comment]
@1307super  你用的PHP那个版本？ 那个分支？  你应该看下 freetype 是否编译成功

有问题慢慢调哈！ 

7.3  版本是需要自己安装gd2 库的 （这个我没调试)


 libavif 和 libxmp 暂时都没有安装 （这两个库静态编译有点麻烦，还没有加入主版本）

![image](https://user-images.githubusercontent.com/6836228/230017063-058852ef-6d92-405f-86d8-442073cf4503.png)

**Comment by 1307super** [comment]
> 

噢噢, 用的是7.3的 我研究研究, 非常感谢~

**Comment by jingjingxyk** [comment]
libXpm  和 libavif 都不太好静态编译，主要这两个库还依赖其他库，暂时没解决这个问题

**Comment by 1307super** [comment]
@jingjingxyk 
使用官网下载的mac版: swoole-cli-5.0.2, 执行composer的时候 会报错, 使用其他集成环境的php执行composer的时候正常, 请问一下您有遇到过吗?
![1681103844779](https://user-images.githubusercontent.com/35326304/231151284-8dfe657c-a4df-4e8b-a572-a0bd193ac076.jpg)

**Comment by 1307super** [comment]
> @1307super 这个问题是个bug （#80 ），静态编译ICU 库时 ICU-DATA 没有设置静态编译 ，已经解决了
> 
> 大佬没有更新已经发布的包

大佬, 又来麻烦您了, 我拉了master的代码, 在另一个mac上编译的, 文档写的brew需写在的依赖都卸载了, 编译好的swoole-cli给到其他mac运行的时候, 都会提示, 已经编译了3次了噶... 都是这个问题, 能帮忙看看吗
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/35326304/233215497-22278ed8-47e6-4df0-a5f2-3c85d45e1377.png">

**Comment by jingjingxyk** [comment]
@1307super 
我擦，我忘了更新 macOS 下的文档了
这样解决
```bash

brew install gettext coreutils

```

**Comment by 1307super** [comment]
> @1307super 我擦，我忘了更新 macOS 下的文档了 这样解决
> 
> ```shell
> brew install gettext coreutils
> ```
> 
> 伴随着个这个 PR 提交的 https://github.com/swoole/swoole-cli/pull/90/files#diff-3d3699e6402f81b8ec7d22543c4a9ed5b1849d2defba09337bc6c37bbd429331 可以看Dockerfile 增加项

收到 非常感谢 ~ 我刚把brew安装的所有依赖给卸载了, 再来一次看看
