### ISSUE TITLE
希望能添加一个xlswriter扩展 excel扩展

### ISSUE THREAD

**Issue by zhufq** [swoole/swoole-cli#42]
希望能添加一个xlswriter扩展 excel扩展  谢谢峰哥！

**Comment by jingjingxyk** [comment]
@zhufq  
自己编译添加即可:

参照：  编译libxlsxwriter 库 ：  https://github.com/jingjingxyk/swoole-cli/blob/1ffb277dd93b70385f12022f1862fa3ac65c5003/library_install_builder_test.php#L1642
编译xlswriter扩展 ： https://github.com/jingjingxyk/swoole-cli/blob/new_dev_build/conf.d/xlswriter.php

参考例子备注说明：当前处于验证中

**Comment by nekic** [comment]
php prepare.php +xlswriter 构建完成后 swoole-cli -m 依然没有 xlswriter 扩展 @jingjingxyk

**Comment by jingjingxyk** [comment]
编译不出来是正常，因为还有好几个PR 没有合并
