### ISSUE TITLE
Makefile:14198

### ISSUE THREAD

**Issue by AR5319** [swoole/swoole-cli#449]
while installing the openssl in raspbian i had faced this issue

make[1]: *** [Makefile:14198: crypto/aes/libcrypto-lib-bsaes-armv8.o] Error 1
make[1]: Leaving directory '/home/ar/Adafruit_python_DHT/openssl'
make: *** [Makefile:3579: build_libs] Error 2

can anyoby help me please

**Comment by jingjingxyk** [comment]
default build support  alpine aarch64 


change  this file： 
      https://github.com/swoole/swoole-cli/blob/main/sapi/src/builder/library/openssl.php#L20


openssl build options: 
          https://github.com/openssl/openssl/blob/master/INSTALL.md#building-openssl

**Comment by jingjingxyk** [comment]
默认支持 alpine x86_64 、aarch64 ; macos 环境下构建

**Comment by jingjingxyk** [comment]
with docker on linux

**Comment by jingjingxyk** [comment]
linux  下 在alpine 容器内构建
