### ISSUE TITLE
[建议] 建议版本号跟PHP版本号保持一致

### ISSUE THREAD

**Issue by tourze** [swoole/swoole-cli#5]
新接触的人很难理解两边的差异，徒增成本。

**Comment by zhao186** [comment]
赞同,之前下载的cli 4.8.*内置的是php8.0,今天下载的 4.8.*新版的就是php8.1,有时候修复swoole-cli的问题把php版本升级了反而会导致项目代码兼容性出问题

**Comment by zhao186** [comment]
建议 
4.8.*一直就php8.0
5.0.*一直就php8.1
每个大版本或子版本不要修改php版本

**Comment by matyhtf** [comment]
@zhao186 目前 4.8 一直是 8.1 ，从 4.8.13 会降低到 php-8.0 ，锁定版本。

@tourze 版本号与 swoole 一致

**Comment by zhao186** [comment]
> @zhao186 目前 4.8 一直是 8.1 ，从 4.8.13 会降低到 php-8.0 ，锁定版本。
> 
> @tourze 版本号与 swoole 一致
thank you
