### ISSUE TITLE
是否不支持macos11

### ISSUE THREAD

**Issue by LTaooo** [swoole/swoole-cli#503]
hfy@HFYdeiMac ~ % ./swoole-cli 
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/lt/./swoole-cli (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/lt/./swoole-cli

**Comment by jingjingxyk** [comment]
对于支持老版本，需要你自己构建。用 macos 11 的环境自己构建

构建步骤：
```bash 

git clone -b main https://github.com/swoole/swoole-cli.git
cd swoole-cli
git submodule update --init

bash setup-php-runtime.sh --mirror china

composer install

php prepare.php

# 查看可用的构建命令
bash make.sh -h


# 静态编译依赖库
bash make.sh  all-library

# 静态编译 PHP 预处理
bash make.sh config

# 静态编译PHP （编译、汇编、链接）
bash make.sh build

# 静态编译PHP （打包）
bash make.sh archive

```

要支持其它版本PHP ，使用 build_native_php 分支，如下：

```bash

php prepare.php --with-php-version=8.2.6


```

**Comment by jingjingxyk** [comment]
简易辅助构建工具： https://swoole-cli-ui.jingjingxyk.com/

**Comment by LTaooo** [comment]
感谢
