### ISSUE TITLE
5.1 编译pdo 协程 有适配的方案吗？

### ISSUE THREAD

**Issue by netyum** [swoole/swoole-cli#554]
比如，加入enable-swoole-sqlite  或者 加入 pdo_pgsql

**Comment by jingjingxyk** [comment]
有的,这里： https://github.com/swoole/swoole-cli/pull/464/files#diff-5d3fd6cbc747b8611ad9835d0478e0a3284e5df664b4faa7477c49ddd7edf9f5R18



分支： ` experiment`   、`build_native_php`   默认已经启用了 ，自己编译，也可以这里下载:

https://github.com/jingjingxyk/swoole-cli/releases/tag/swoole-cli-v0.0.4
https://github.com/swoole/build-static-php/releases

**Comment by netyum** [comment]
这没开启pdo_pgsql 和pdo_sqlite吧！！

**Comment by jingjingxyk** [comment]
> 这没开启pdo_pgsql 和pdo_sqlite吧！！

swoole 内置了，详见这里： https://github.com/swoole/swoole-src/tree/master/thirdparty/php81

同时启用，编译的时候出现:  函数多重定义

**Comment by netyum** [comment]
你是说， 不开启，也可以使用pdo吗？

**Comment by jingjingxyk** [comment]
> 你是说， 不开启，也可以使用pdo吗？

是的 https://wiki.swoole.com/#/environment?id=-enable-swoole-pgsql

**Comment by netyum** [comment]
好的，我用你的分支试试

**Comment by matyhtf** [comment]
已提供：

https://www.swoole.com/download
