### ISSUE TITLE
大佬，常用的国标加密库能不能加进去？

### ISSUE THREAD

**Issue by findnr** [swoole/swoole-cli#555]
项目中经常用到国标的加密，在github上看一到一个大佬写PHP扩展库，地址：https://github.com/GmSSL/GmSSL-PHP ，如果能集成进去的话会方便很多，主要是我想集成进去，但是自己又没有那个能力。

**Comment by NathanFreeman** [comment]
openssl版本大于1.0.d的话，就可以使用国密加密

**Comment by jingjingxyk** [comment]
@findnr  加好了，能否用，还需要编译验证。https://github.com/jingjingxyk/swoole-cli/pull/123/files。 

添加这个文件即可： https://github.com/jingjingxyk/swoole-cli/blob/feature-ext-gmssl/sapi/src/builder/extension/gmssl.php

在`experiment`  分支基础上添加即可变异验证

**Comment by findnr** [comment]
谢谢大佬

**Comment by jingjingxyk** [comment]
https://github.com/swoole/swoole-cli/issues/555#issuecomment-1884147343
