### ISSUE TITLE
swoole-cli 5.1.1 不支持php-fpm运行了吗？

### ISSUE THREAD

**Issue by reegle** [swoole/swoole-cli#577]
sudo ./swoole-mac -P --fpm-config /Users/xxx/swoole/php-fpm-8.1.conf -p /Users/xxx/site/swoole/81 -F

我用5.01的可以运行，5.1.1运行就提示下面的
![488CF28085A625C2A15217E9904E267D](https://github.com/swoole/swoole-cli/assets/35456723/bae88984-6235-4ade-9b2c-85293de446ec)

**Comment by jingjingxyk** [comment]
fixbug: https://github.com/swoole/swoole-cli/releases/tag/v5.1.2.0
