### ISSUE TITLE
Cygwin 环境中的这个 swoole-cli 似乎不能够很好的支持 phpstan

### ISSUE THREAD

**Issue by vkviyu** [swoole/swoole-cli#584]
![image](https://github.com/swoole/swoole-cli/assets/90970572/c82ffc8c-283a-4cd3-b064-0c41cae33873)
当我使用： php vendor/bin/phpstan analyse ./application/models/Wdt_dev_mdl.php 时会报错 `Child process error` ，但是当我在这条命令上加上 --debug 参数： php vendor/bin/phpstan analyse --debug ./application/models/Wdt_dev_mdl.php 。则可以很好的运行。似乎是 phpstan 在不加 --debug 参数时，就会在一个子进程中运行，而 Cygwin 的 swoole-cli 似乎不能很好的支持这种子进程，所以就报了上面的 exit code 127 的错误？

**Comment by jingjingxyk** [comment]
可参考这个： https://wenda.swoole.com/detail/108885
