### ISSUE TITLE
build提示 ext/phar/phar_internal.h:619:1: error: expected identifier or '('

### ISSUE THREAD

**Issue by taobali32** [swoole/swoole-cli#603]
![image](https://github.com/swoole/swoole-cli/assets/30717763/11256b0c-59b5-4bfe-b0c8-143aae7fd6b5)

使用的是官方提供的base镜像，
运行的命令是 bash make.sh build 然后就报错了
![image](https://github.com/swoole/swoole-cli/assets/30717763/a3c75beb-84ee-44d4-a45c-8dbd120d3976)

**Comment by jingjingxyk** [comment]
你查看下你本地的源代码代码

也就是这个文件，619行，看看是否有错误
https://github.com/swoole/swoole-cli/blob/main/ext/phar/phar_internal.h


先看下查看一下619行
```
cat ext/phar/phar_internal.h

```

可参照这个脚本，一条命令构建完毕

https://github.com/swoole/swoole-cli/blob/main/build-release-example.sh

**Comment by jingjingxyk** [comment]
或者参考这里： https://github.com/swoole/swoole-cli/issues/504

**Comment by jingjingxyk** [comment]
linux 环境下构建，需要容器外执行一遍，容器内执行一遍如下命令
```

php prepare.php

```

**Comment by taobali32** [comment]
#see https://www.yuque.com/u2401684/ye23db/rwlv2dmmf1a3aktg?singleDoc# 《swoole-cli》
