### ISSUE TITLE
Warning: exec(): Unable to fork

### ISSUE THREAD

**Issue by niceboyat** [swoole/swoole-cli#675]
win10下cmd运行：
`swoole-cli -f ./test.php`

test.php文件代码：
`<?php exec('dir', $str, $code); ?>`

出现这个错误：
```
Warning: exec(): Unable to fork [dir] in /usr/bin/test.php on line 1
```

**Comment by niceboyat** [comment]
但是，当用PHP原端的时候就没问题
win10下cmd运行：
php -f ./test.php

test.php文件代码不变

输出：
int(0)

**Comment by jingjingxyk** [comment]
错误提示产生的代码： 
https://github.com/swoole/swoole-cli/blob/bf6a2448fa421ed9dd661de17c83116fc5a2b973/ext/standard/exec.c#L136C3-L136C65

需要研究下

**Comment by niceboyat** [comment]
> 错误提示产生的代码： https://github.com/swoole/swoole-cli/blob/bf6a2448fa421ed9dd661de17c83116fc5a2b973/ext/standard/exec.c#L136C3-L136C65
> 
> 需要研究下

难道是PHP_WIN32没有定义，导致if判断为false?

**Comment by jingjingxyk** [comment]
你试一下 shell_exec 是不是也不好使。

**Comment by niceboyat** [comment]
> 你试一下 shell_exec 是不是也不好使。 不添加 -f 参数也试试，是否也报错

win10下cmd运行：
swoole-cli -f ./test.php

test.php文件代码：
<?php $code = shell_exec('dir');var_dump($code); ?>

报错：
Warning: shell_exec(): Unable to execute 'dir' in /usr/bin/test.php on line 1
bool(false)

上面版本是swoole-cli v5.1.3
换版本swoole-cli v4.8.13，报错不变

想问一下PHP_WIN32在哪里定义的？我查找源码行数，没找到。

**Comment by jingjingxyk** [comment]
本项目应该是没有定义 PHP_WIN32 ，  因为 windows cygwin 环境下构建，其实是类 linux 环境构建， 这是完整构建配置： https://github.com/swoole/swoole-cli/blob/main/sapi/scripts/cygwin/cygwin-config.sh



windows 原生构建 ,定义 PHP_WIN32 所在文件： https://github.com/php/php-src/blob/php-8.1.27/win32/build/confutils.js#L3227 



1. linux        原生构建 执行的是 `./buildconf --force` ，具体文件： https://github.com/php/php-src/blob/php-8.1.27/buildconf.bat
2. windows 原生构建 执行的是 `buildconf.bat --f `   ， 具体文件： https://github.com/php/php-src/blob/php-8.1.27/buildconf.bat

**Comment by jingjingxyk** [comment]
windows 构建配置在这个目录： https://github.com/php/php-src/tree/php-8.1.27/win32/build

**Comment by niceboyat** [comment]
请了两位朋友测试，一位是windows10,一位是windows Server 2019，都发生一致的错误，这个应该是bug了。

**Comment by jingjingxyk** [comment]
可定制一下编译参数试试，找到这个文件 https://github.com/swoole/swoole-cli/blob/main/sapi/scripts/cygwin/cygwin-config.sh

添加这一行
```bash

export CFLAGS="-DZEND_WIN32=1 "

```

类似这个，实验一下，看能否解决
![image](https://github.com/swoole/swoole-cli/assets/6836228/559cf38f-1b6c-47cd-ac0b-b9c10598b7a6)


实验pr : https://github.com/swoole/swoole-cli/pull/680/files

**Comment by jingjingxyk** [comment]
看 VCWD_POPEN 函数的定义： 位于  https://github.com/swoole/swoole-cli/tree/main/Zend/zend_virtual_cwd.h 文件

![image](https://github.com/swoole/swoole-cli/assets/6836228/d9dbf928-ed8d-424d-9211-ec3e78cb79aa)

**Comment by jingjingxyk** [comment]
可实验添加的参数
```bash

export CFLAGS="-DZEND_WIN32=1 -DPHP_WIN32=1 -DWIN32 "
# https://github.com/php/php-src/blob/php-8.1.27/win32/build/confutils.js#L3227

```

**Comment by jingjingxyk** [comment]
查看编译结果： https://github.com/swoole/swoole-cli/actions/runs/9833711486/job/27144355874

**Comment by jingjingxyk** [comment]
[windows版swoole-cli 函数shell_exec Unable to execute](https://wenda.swoole.com/detail/108846)

**Comment by jingjingxyk** [comment]
@niceboyat  你试试 不添加 -f 执行，报错吗？

**Comment by niceboyat** [comment]
> @niceboyat 你试试 不添加 -f 执行，报错吗？

不添加-f执行，也报错。

**Comment by niceboyat** [comment]
> [windows版swoole-cli 函数shell_exec Unable to execute](https://wenda.swoole.com/detail/108846)

稍后我试一下完整cygwin环境

**Comment by 1808661305** [comment]
我测试不添加-f也不行

**Comment by niceboyat** [comment]
> 我测试不添加-f也不行

辛苦了。

**Comment by ooing** [comment]
我也提示 ErrorException: exec(): Unable to fork [/cygdrive/c/Windows/system32/notepad.exe]

**Comment by ooing** [comment]
"shell_exec(): Unable to execute 'pwd'"

**Comment by jingjingxyk** [comment]
此问题依然存在

<img width="1372" alt="Image" src="https://github.com/user-attachments/assets/855f8e90-1e30-424a-8a54-45a820614c08" />

**Comment by ooing** [comment]
@jingjingxyk  这个问题 挺影响windows版本的swoole-cli 使用，能否看下 ，谢谢
