### ISSUE TITLE
每天都在关注，提一个想法

### ISSUE THREAD

**Issue by etjson** [swoole/swoole-cli#8]
一直在关注cli的更新情况，希望可以支持把`hyperf`框架打包的`phar`包直接编译进cli，这样分发出去只要给一个文件就够了

**Comment by matyhtf** [comment]
虽然通过各种奇技淫巧能实现这样的功能，但是这个并不是真正的编译php代码为机器码然后构建成为一个可执行程序。 

php 语言只是一个脚本语言，它的运行方式就是使用 VM 加载执行的方式。强行整合为一个可执行文件，具有一定的迷惑性。

就像 java 程序，都是通过先安装 jre 再通过 `java your_app.jar` 的方式运行的。


分发问题
---
`swoole-cli`已经解决了分发的问题，你可以把 swoole-cli 和 你的php 程序一起打包给用户即可。
这里何必纠结于分发一个文件，还是两个文件呢，这并没有什么区别。


授权问题
---
`swoole-cli`中使用了很多`GPL`协议的软件包，这些软件包是有授权污染的问题的，若要将`swoole-cli`的二进制程序进行发行，相关的源代码必须是开源的。

如果你坚持要将你的 php 代码和 `swoole-cli` 打包在一起，可能会有法律风险，这可能会被视为发行程序的一部分，你的 php 代码可能也需要开源。

**Comment by TNT-ma** [comment]
> 虽然通过各种奇技淫巧能实现这样的功能，但是这个并不是真正的编译php代码为机器码然后构建成为一个可执行程序。
> 
> php 语言只是一个脚本语言，它的运行方式就是使用 VM 加载执行的方式。强行整合为一个可执行文件，具有一定的迷惑性。
> 
> 就像 java 程序，都是通过先安装 jre 再通过 `java your_app.jar` 的方式运行的。
> 
> ## 分发问题
> `swoole-cli`已经解决了分发的问题，你可以把 swoole-cli 和 你的php 程序一起打包给用户即可。 这里何必纠结于分发一个文件，还是两个文件呢，这并没有什么区别。
> 
> ## 授权问题
> `swoole-cli`中使用了很多`GPL`协议的软件包，这些软件包是有授权污染的问题的，若要将`swoole-cli`的二进制程序进行发行，相关的源代码必须是开源的。
> 
> 如果你坚持要将你的 php 代码和 `swoole-cli` 打包在一起成为一个可执行文件，可能会有法律风险，这可能会被视为发行程序的一部分，你的 php 代码可能也需要开源。

说了一堆也没有说清楚 如何把 phar 和 swoole 整合为一个文件

**Comment by jingjingxyk** [comment]
@etjson swoole-cli 本质是PHP 运行时（PHP 解释器）。 

phar打包也只是把多个文件归档到同一个可压缩的文件中。 phar打包也没有生成字节码


```text
类似：

wrap( php-rumtime + app.phar)

```

https://www.php.net/manual/zh/wrappers.phar.php

**Comment by jingjingxyk** [comment]
> phar 和 swoole

php 运行时包含swoole。你想要的是  php运行时+用户运用程序打成一个可执行包。

**Comment by jingjingxyk** [comment]
[AppImage](https://appimage.org/)
[flatpak](https://docs.flatpak.org/en/latest/building.html)

**Comment by TNT-ma** [comment]
> > phar 和 swoole
> 
> php 运行时包含swoole。你想要的是 php运行时+用户运用程序打成一个可执行程序。

就如同：static-php-cli 项目：cat micro.sfx my.phar > single-app
single-app 就是一个PHP +  my.phar 组合一起的二进制文件
swoole-cli 不可行

**Comment by jingjingxyk** [comment]
@TNT-ma 看这里 https://github.com/swoole/swoole-cli/pull/55 ，小伙伴在弄了哦

**Comment by jingjingxyk** [comment]
@TNT-ma  试一试这是你想要的的功能，https://github.com/swoole/swoole-cli/tree/main/samples/sfx 小伙伴完成了，试一试
