### ISSUE TITLE
5.1.5  出了吗  怎么版本号还是5.1.4

### ISSUE THREAD

**Issue by LIngMax** [swoole/swoole-cli#818]
![image](https://github.com/user-attachments/assets/93717a2e-f5c9-485c-8bc7-32a69e7980b5)

**Comment by jingjingxyk** [comment]
> ![image](https://private-user-images.githubusercontent.com/57652032/381011197-93717a2e-f5c9-485c-8bc7-32a69e7980b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDQ0MTYsIm5iZiI6MTczMDIwNDExNiwicGF0aCI6Ii81NzY1MjAzMi8zODEwMTExOTctOTM3MTdhMmUtZjVjOS00ODVjLThiYzctMzJhNjllNzk4MGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEyMTUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMjFmMmI0MDc1ZTE0ZGZkNmU3YTRjNTYxMmYzZmMyMzU0MTU0Zjc5NThkODJjYjg0MGM3OTJkZGJlYzc1MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HUcMGUgvAU3RtPuMt4dIzU1sL7IvWHcEgIFsx1iJ9q0)

发版的时候，忘了合并这个 https://github.com/swoole/swoole-cli/pull/810
