### ISSUE TITLE
能将xlswriter作为常用扩展固定到swoole-cli之后的版本中吗？

### ISSUE THREAD

**Issue by long2651** [swoole/swoole-cli#835]
swoole-cli 5.1.4版本有xlswriter到5.1.5版本又没有了，能将xlswriter作为常用扩展固定到swoole-cli之后的版本中吗？

**Comment by jingjingxyk** [comment]
> swoole-cli 5.1.4版本有xlswriter到5.1.5版本又没有了，能将xlswriter作为常用扩展固定到swoole-cli之后的版本中吗？

将xlswriter作为常用扩展固定到swoole-cli之后的版本中  @matyhtf 


其它解决办法：
 fork 本项目，启用 github runner action ，在此[enabled_extensions.php](https://github.com/swoole/swoole-cli/blob/main/sapi/src/builder/enabled_extensions.php)文件中添加 xlswriter 。打个 tag 即可，就会自动构建你需要的 swoole-cli

**Comment by jingjingxyk** [comment]
或者用这个： https://github.com/swoole/build-static-php/releases/tag/v1.5.2

**Comment by jingjingxyk** [comment]
https://github.com/swoole/swoole-cli/pull/838

**Comment by long2651** [comment]
@jingjingxyk @matyhtf 感谢两位大佬！
