### ISSUE TITLE
swoole-cli-v5.1.6仍然没有xslwriter

### ISSUE THREAD

**Issue by long2651** [swoole/swoole-cli#845]
https://github.com/swoole/swoole-cli/issues/835
下载使用文件为swoole-cli-v5.1.6-linux-x64.tar.xz仍然没有xslwriter

**Comment by jingjingxyk** [comment]
配置文件里 单词写错了
![image](https://github.com/user-attachments/assets/e6db5e9a-6506-40a2-ab91-cf120623b3e0)

正确的单词 应该是： xlswriter

**Comment by jingjingxyk** [comment]
> #835 下载使用文件为swoole-cli-v5.1.6-linux-x64.tar.xz仍然没有xslwriter

https://github.com/swoole/swoole-cli/pull/846/files
