### ISSUE TITLE
编译报错，麻烦问一下各位大佬，这是代码有问题吗？

### ISSUE THREAD

**Issue by findnr** [swoole/swoole-cli#858]
![image](https://github.com/user-attachments/assets/e79368c1-4ecc-410d-929f-628e9888d8df)

**Comment by jingjingxyk** [comment]
> ![image](https://private-user-images.githubusercontent.com/3909023/393495020-e79368c1-4ecc-410d-929f-628e9888d8df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Njc4NTYsIm5iZiI6MTczMzU2NzU1NiwicGF0aCI6Ii8zOTA5MDIzLzM5MzQ5NTAyMC1lNzkzNjhjMS00ZWNjLTQxMGQtOTI5Zi02MjhlOTg4OGQ4ZGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDdUMTAzMjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTdjYWIxNTMwNzE3ZTAyOTU0ZDhjYmUxZTE4NWNlZjNmMGVmYTZjZTg2ZmFiNDc2NDg3NzA0OTc4YWY5MjM4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zHKr2KsWNUZquYlJF3CzgqDsqLl0UjFMv3yhd3omJUw)

如何复现？
构建参数是什么？

**Comment by findnr** [comment]
docker pull alpine
git clone --recursive https://github.com/swoole/swoole-cli.git
cd swoole
bash setup-php-runtime.sh
composer install
php prepare.php
php prepare.php +inotify +mongodb +xlswriter
chmod 777 make.sh
docker run -ti --name swoole-cli-mian -v /mnt/swoole/swoole-cli:/work alpine /bin/sh
cd work
sh  sapi/quickstart/linux/alpine-init.sh
./make.sh all-library
./make.sh config
./make.sh build

**Comment by jingjingxyk** [comment]
![image](https://github.com/user-attachments/assets/38390f9f-4292-4cdc-a38b-e69e9bc37eb1)

**Comment by jingjingxyk** [comment]
> docker pull alpine git clone --recursive https://github.com/swoole/swoole-cli.git cd swoole bash setup-php-runtime.sh composer install php prepare.php php prepare.php +inotify +mongodb +xlswriter chmod 777 make.sh docker run -ti --name swoole-cli-mian -v /mnt/swoole/swoole-cli:/work alpine /bin/sh cd work sh sapi/quickstart/linux/alpine-init.sh ./make.sh all-library ./make.sh config ./make.sh build


> https://github.com/swoole/swoole-cli/blob/main/docs/linux.md
```shell
git clone --recursive https://github.com/swoole/swoole-cli.git
cd swoole
bash setup-php-runtime.sh
composer install
php prepare.php
php prepare.php +inotify +mongodb +xlswriter
bash make.sh docker-build 
# 进入容器
bash make.sh docker-bash 

bash setup-php-runtime.sh
export PATH=$PATH:/work/bin/runtime

# 再次生成 make.sh 
php prepare.php +inotify +mongodb +xlswriter

./make.sh all-library
./make.sh config
./make.sh build


```

**Comment by jingjingxyk** [comment]
当前： 容器 alpine 版本 设置为 3.17、3.18 。其他版本还没测试

**Comment by findnr** [comment]
嗯，果然是换到3.17版本就可以了，非常OK，感谢大佬！！！
