### ISSUE TITLE
[Feature Request] 补充常用的PHP扩展

### ISSUE THREAD

**Issue by tourze** [swoole/swoole-cli#9]
例如 apcu、ffi 这些能力，我看默认都没打包进来。

**Comment by matyhtf** [comment]
欢迎提交 pr ，修改 `conf.d` 增加相应扩展即可，参考 `redis`

**Comment by jingjingxyk** [comment]
apcu 扩展： https://github.com/jingjingxyk/swoole-cli/blob/dev-pgsql/conf.d/apcu.php
ffi 扩展： https://github.com/jingjingxyk/swoole-cli/blob/dev-pgsql/conf.d/ffi.php
ffi 扩展依赖库： https://github.com/jingjingxyk/swoole-cli/blob/ff995f9924888c9dc6788d3dc0fee817a463dc87/prepare.php#L1294
